### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by pgoodman** [AliveToolkit/alive2#225] opened 2019-12-13 19:40 UTC
```
FAIL: Alive2 :: alive-tv/constexpr/aggregate.src.ll (1 of 219)
FAIL: Alive2 :: alive-tv/constexpr/ret.src.ll (2 of 219)
FAIL: Alive2 :: alive-tv/glbconstchk.src.ll (3 of 219)
FAIL: Alive2 :: alive-tv/constexpr/aggregate2.src.ll (4 of 219)
FAIL: Alive2 :: alive-tv/dbg.src.ll (5 of 219)
FAIL: Alive2 :: alive-tv/constexpr/aggregate3.src.ll (6 of 219)
FAIL: Alive2 :: alive-tv/constexpr/constgep-fail.src.ll (7 of 219)
FAIL: Alive2 :: alive-tv/constexpr/loadgep-fail.src.ll (8 of 219)
FAIL: Alive2 :: alive-tv/constexpr/loadgep.src.ll (9 of 219)
FAIL: Alive2 :: alive-tv/constexpr/string.src.ll (10 of 219)
FAIL: Alive2 :: alive-tv/constexpr/phigep-fail.src.ll (11 of 219)
FAIL: Alive2 :: alive-tv/constexpr/shufflevector-nocopy.src.ll (12 of 219)
FAIL: Alive2 :: alive-tv/glbconstchk2.src.ll (13 of 219)
FAIL: Alive2 :: alive-tv/constexpr/constgep.src.ll (14 of 219)
FAIL: Alive2 :: alive-tv/constexpr/ptrdiff.src.ll (15 of 219)
FAIL: Alive2 :: alive-tv/constexpr/zeroinitializer.src.ll (16 of 219)
FAIL: Alive2 :: alive-tv/constexpr/phigep.src.ll (17 of 219)
FAIL: Alive2 :: alive-tv/memory-opt/bwiden_4.src.ll (18 of 219)
FAIL: Alive2 :: alive-tv/glbsizechk.src.ll (19 of 219)
FAIL: Alive2 :: alive-tv/memory-opt/bwiden-calloc.src.ll (20 of 219)
FAIL: Alive2 :: alive-tv/constexpr/cycle.src.ll (21 of 219)
FAIL: Alive2 :: alive-tv/freeze.src.ll (22 of 219)
FAIL: Alive2 :: alive-tv/memory-opt/bwiden_8.src.ll (23 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-bigendian.src.ll (24 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-i2.src.ll (25 of 219)
FAIL: Alive2 :: alive-tv/memory-opt/bwiden_2.src.ll (26 of 219)
FAIL: Alive2 :: alive-tv/infinite-loop.src.ll (27 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-fail-3.src.ll (28 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-vector.src.ll (29 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-fail-2.src.ll (30 of 219)
FAIL: Alive2 :: alive-tv/globalopt.src.ll (31 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-disjoint.src.ll (32 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-fail-1.src.ll (33 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate.src.ll (34 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-address-nonnull.src.ll (35 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-malloc-fail.src.ll (36 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-disjoint-fail.src.ll (37 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-malloc.src.ll (38 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-calloc.src.ll (39 of 219)
FAIL: Alive2 :: alive-tv/memory/aggregate-vector-bigendian.src.ll (40 of 219)
FAIL: Alive2 :: alive-tv/memory/alloca-uninit.src.ll (41 of 219)
FAIL: Alive2 :: alive-tv/memory/bigendian-fail.src.ll (42 of 219)
FAIL: Alive2 :: alive-tv/memory/array-gep.src.ll (43 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-init.src.ll (44 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-free-noub.src.ll (45 of 219)
FAIL: Alive2 :: alive-tv/memory/bigendian.src.ll (46 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-overflow.src.ll (47 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-doublefree-fail.src.ll (48 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-alloca.src.ll (49 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-init-fail.src.ll (50 of 219)
FAIL: Alive2 :: alive-tv/memory/free-null-fail.src.ll (51 of 219)
FAIL: Alive2 :: alive-tv/memory/free-noub-2.src.ll (52 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-overflow-2.src.ll (53 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-glb.src.ll (54 of 219)
FAIL: Alive2 :: alive-tv/memory/calloc-undef.src.ll (55 of 219)
FAIL: Alive2 :: alive-tv/memory/free-noub.src.ll (56 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-useafterfree-1.src.ll (57 of 219)
FAIL: Alive2 :: alive-tv/memory/free-null.src.ll (58 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-gep.src.ll (59 of 219)
FAIL: Alive2 :: alive-tv/memory/freshbid-alloca-2.src.ll (60 of 219)
FAIL: Alive2 :: alive-tv/memory/freshbid-new.src.ll (61 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-null.src.ll (62 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-useafterfree-2.src.ll (63 of 219)
FAIL: Alive2 :: alive-tv/memory/freshbid-malloc-2.src.ll (64 of 219)
FAIL: Alive2 :: alive-tv/memory/free-ub-doublefree.src.ll (65 of 219)
FAIL: Alive2 :: alive-tv/memory/freshbid-alloca-1.src.ll (66 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-2.src.ll (67 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-1.src.ll (68 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-null2.src.ll (69 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-3.src.ll (70 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-5.src.ll (71 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-address-nonnull.src.ll (72 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-alloca-disjoint-fail.src.ll (73 of 219)
FAIL: Alive2 :: alive-tv/memory/freshbid-malloc-1.src.ll (74 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-struct1.src.ll (75 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-align-fail.src.ll (76 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-vector.src.ll (77 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-struct2.src.ll (78 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-align.src.ll (79 of 219)
FAIL: Alive2 :: alive-tv/memory/gep-struct1-fail.src.ll (80 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-alloca-disjoint.src.ll (81 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-alloca-noalias.src.ll (82 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-anonymous-2.src.ll (83 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-anonymous.src.ll (84 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-arg-noalias-fail-1.src.ll (85 of 219)
FAIL: Alive2 :: alive-tv/memory/malloc-large.src.ll (86 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-arg-noalias-fail-2.src.ll (87 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-disjoint.src.ll (88 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-externconst.src.ll (89 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-fail-2.src.ll (90 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-fail-1.src.ll (91 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-reorder.src.ll (92 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-malloc-noalias.src.ll (93 of 219)
FAIL: Alive2 :: alive-tv/memory/glb-disjoint-fail.src.ll (94 of 219)
FAIL: Alive2 :: alive-tv/memory/malloc-large-error.src.ll (95 of 219)
FAIL: Alive2 :: alive-tv/memory/memset-store.src.ll (96 of 219)
FAIL: Alive2 :: alive-tv/memory/malloc-oom.src.ll (97 of 219)
FAIL: Alive2 :: alive-tv/memory/memset-store-fail.src.ll (98 of 219)
FAIL: Alive2 :: alive-tv/memory/memcpy-1.src.ll (99 of 219)
FAIL: Alive2 :: alive-tv/memory/memcpy-memset-1.src.ll (100 of 219)
FAIL: Alive2 :: alive-tv/memory/memcpy-memset-2.src.ll (101 of 219)
FAIL: Alive2 :: alive-tv/memory/memset-1.src.ll (102 of 219)
FAIL: Alive2 :: alive-tv/memory/memset-fn.src.ll (103 of 219)
FAIL: Alive2 :: alive-tv/memory/new-null-fail.src.ll (104 of 219)
FAIL: Alive2 :: alive-tv/memory/malloc-null.src.ll (105 of 219)
FAIL: Alive2 :: alive-tv/memory/punning-ptrint.src.ll (106 of 219)
FAIL: Alive2 :: alive-tv/memory/pre-bigendian.src.ll (107 of 219)
FAIL: Alive2 :: alive-tv/memory/nullptr-fail.src.ll (108 of 219)
FAIL: Alive2 :: alive-tv/memory/ptrtoint-free-reorder-fail.src.ll (109 of 219)
FAIL: Alive2 :: alive-tv/memory/ptrtoint-free-reorder.src.ll (110 of 219)
FAIL: Alive2 :: alive-tv/memory/nullptr.src.ll (111 of 219)
FAIL: Alive2 :: alive-tv/memory/malloc-undef.src.ll (112 of 219)
FAIL: Alive2 :: alive-tv/memory/punning-intptr.src.ll (113 of 219)
FAIL: Alive2 :: alive-tv/memory/punning-floatint.src.ll (114 of 219)
FAIL: Alive2 :: alive-tv/memory/store-nan.src.ll (115 of 219)
FAIL: Alive2 :: alive-tv/memory/storeptr.src.ll (116 of 219)
FAIL: Alive2 :: alive-tv/memory/storeptr-fail.src.ll (117 of 219)
FAIL: Alive2 :: alive-tv/memory/undefptr.src.ll (118 of 219)
FAIL: Alive2 :: alive-tv/refinement/const-fail.src.ll (119 of 219)
FAIL: Alive2 :: alive-tv/refinement/global-fail.src.ll (120 of 219)
FAIL: Alive2 :: alive-tv/refinement/nonlocal-fail.src.ll (121 of 219)
FAIL: Alive2 :: alive-tv/refinement/local.src.ll (122 of 219)
FAIL: Alive2 :: alive-tv/unreachable-1.src.ll (123 of 219)
FAIL: Alive2 :: alive-tv/refinement/global.src.ll (124 of 219)
FAIL: Alive2 :: alive-tv/unreachable-2.src.ll (125 of 219)
FAIL: Alive2 :: alive-tv/unreachable-fail.src.ll (126 of 219)
FAIL: Alive2 :: alive-tv/ret-fail.src.ll (127 of 219)
FAIL: Alive2 :: alive-tv/unreachable-void-2.src.ll (128 of 219)
FAIL: Alive2 :: alive-tv/unreachable-void-1.src.ll (129 of 219)
```

LLVM 10.0, head of master branch of alive2.

**Comment by regehr** [comment] 2019-12-13 19:54
Ok, this is not expected and not what I see. What version of Z3 are you using?

**Comment by aqjune** [comment] 2019-12-13 19:54
Are your executables (alive, alive-tv) placed at `build` directory (as the readme said)?

**Comment by regehr** [comment] 2019-12-13 20:07
I currently (on a Mac, using a very recent LLVM and Z3 4.8.7) get one test failure, this one doesn't go even with a very generous timeout:
```./alive-tv ../tests/alive-tv/memory/freshbid-malloc-2.src.ll ../tests/alive-tv/memory/freshbid-malloc-2.tgt.ll --smt-to=30000```

**Comment by regehr** [comment] 2019-12-13 20:12
also, please provide here the CMake invocation you used

**Comment by aqjune** [comment] 2019-12-13 20:12
@regehr The newer Z3 might resolve the problem. The test passes when `Z3 version 4.8.8 - 64 bit` (master, cdf3c48) is used.

**Comment by regehr** [comment] 2019-12-13 20:18
thanks, I will upgrade!

also your diagnosis of Peter's problem as something specific to alive-tv seems correct, it is only those tests that are failing...

**Comment by pgoodman** [comment] 2019-12-13 21:40
As far as I can tell, the issue seems to be that `alive-tv` doesn't correctly link against libz3. E.g. 

```
root@llvmizer:~/alive2/build# ldd alive-tv 
	linux-vdso.so.1 (0x00007ffe013fd000)
	libz3.so.4.8 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb6d8224000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb6d7e9b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb6d7afd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb6d78e5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6d74f4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6d8abf000)
```

When I run John's command from above, prefixed with `LD_LIBRARY_PATH=/usr/local/lib`, I see results. When I run the python test runner with this environment variable set, the results I get are: 

```
  Expected Passes    : 70
  Expected Failures  : 1
  Unresolved Tests   : 147
  Unexpected Failures: 1
```

**Comment by regehr** [comment] 2019-12-13 21:45
this is a linux box, Peter?

one possibility is that lit is stripping out an environment variable that you need. I think there's some sort of whitelisting facility but can't remember any detail.

anyhow, I would suggest that you run a couple more test cases by hand and if you are getting positive results, proceed normally and ignore the testing stuff. we may be able to solve it in the background.

**Comment by regehr** [comment] 2019-12-13 21:46
also I have no idea what "Unresolved Tests" are, ugh.

**Comment by pgoodman** [comment] 2019-12-13 21:49
ubuntu 18.04.

**Comment by pgoodman** [comment] 2019-12-13 21:49
using z3 master, and llvm master.

**Comment by aqjune** [comment] 2019-12-14 05:47
That's weird.
Having a libz3.so copy at the build directory might work as a temporary solution.

**Comment by nunoplopes** [comment] 2019-12-26 19:50
I'm closing this for now since neither of us is able to reproduce the issue. If you manage to find the cause and/or fix it please let us know. Thanks!

**Closed by nunoplopes** 2019-12-26 19:50 UTC
