### ISSUE TITLE
No checking done with the new pass manager

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#330] opened 2020-03-22 10:53 UTC
This command checks nothing:
```~/llvm/build/bin/opt -load $HOME/alive2/build/tv/tv.so -tv -passes='simplify-cfg<switch-to-lookup>' -tv ~/llvm/llvm/test/Transforms/SimplifyCFG/switch-dead-default.ll```

**Comment by aqjune** [comment] 2020-12-04 01:43
I'm working on this

**Comment by aqjune** [comment] 2020-12-04 04:00
This turns out to be non-trivial:
From the plugin's view, there's no way to distinguish whether it is from opt or clang.
If we reuse the callback-after-each-pass mechanism that is currently used by clang, then the distinguishing isn't needed, but  the callbacks registered by `registerPipelineStartEPCallback`/`registerOptimizerLastEPCallback` don't fire when opt is used.
I don't think there is a trivial workaround for this. I'll send a mail asking this to llvm-dev.

**Comment by aqjune** [comment] 2020-12-04 08:20
According to the answers, it seems `registerPipelineStartEPCallback/registerOptimizerLastEPCallback` only works when a default pipeline like O2 is given (which is intended).

But it seems okay now because we're explicitly giving `tv` at the beginning and end of the passes..? :)

I'll prepare a patch for this.

**Comment by nunoplopes** [comment] 2020-12-04 10:02
Well I don't want to give up of the option of running TV at whatever time we want. This should still work: `-tv -sroa -tv -instcombine -simplifycfg -tv

**Comment by aqjune** [comment] 2020-12-04 20:46
My patch would preserve the behavior of opt with the legacy pass manager and the clang plugin.
For the new pass manager as well, I think I found a way to support multiple tv options. :)
But I'm struggling with some unexpected behavior of the new pass manager now... will make a PR when it is done

**Comment by aqjune** [comment] 2020-12-08 13:22
Okay, the pass string works like this, This is a description from PassBuilder.cpp:
```
/// The format of the textual pass pipeline description looks something like:
///
/// module(function(instcombine,sroa),dce,cgscc(inliner,function(...)),...)
///
/// Pass managers have ()s describing the nest structure of passes. All passes
/// are comma separated. As a special shortcut, if the very first pass is not
/// a module pass (as a module pass manager is), this will automatically form
/// the shortest stack of pass managers that allow inserting that first pass.
/// So, assuming function passes 'fpassN', CGSCC passes 'cgpassN', and loop
/// passes 'lpassN', all of these are valid:
///
/// fpass1,fpass2,fpass3
/// cgpass1,cgpass2,cgpass3
/// lpass1,lpass2,lpass3
///
/// And they are equivalent to the following (resp.):
///
/// module(function(fpass1,fpass2,fpass3))
/// module(cgscc(cgpass1,cgpass2,cgpass3))
/// module(function(loop(lpass1,lpass2,lpass3)))
///
/// This shortcut is especially useful for debugging and testing small pass
/// combinations. Note that these shortcuts don't introduce any other magic.
/// If the sequence of passes aren't all the exact same kind of pass, it will    < important
/// be an error. You cannot mix different levels implicitly, you must            <
/// explicitly form a pass manager in which to nest passes.
```

For example, consider an LLVM unit test that has:
```
; RUN: opt -passes='loop(unswitch<nontrivial>)' ....
```
Simply adding tv before/after the pass won't work:
```
opt -passes='tv,loop(unswitch<nontrivial>),tv' ....
```
.. unless tv is defined as a loop-level pass, which is a bit strange.

I asked this to llvm-dev, and it can be resolved by fully specifying an adaptor stack:
```
opt -passes='tv,module(function(loop(unswitch<nontrivial>))),tv' ....
```
and defining tv as a module-level pass.
This means that we need a tool that takes a pass string and rewrites it in a fully adaptor-stacked form.
LLVM does not have one yet, and I think I can write one, but does this approach seem okay?
Or, would it be enough if the bitcodes before/after each passes is checked for the new pass manager (as we do for clang tv)?

There are quite a few LLVM unit tests that use NPM (> 1,500) and they use loop-vectorize, scalarizer, etc; supporting those may detect interesting bugs from them.

**Comment by nunoplopes** [comment] 2020-12-08 13:56
This rewrite is essentially take `-passes=x` and rewrite to `-passes=module(adaptor(x))`, where adaptor needs to be one of loop/function/cgscc? If that's the case, opt-alive.sh should be able to handle it.

Can we query opt to tell what's the type of a given pass or do we need to curate the list ourselves?

**Comment by nunoplopes** [comment] 2020-12-08 14:01
Well, this works if nothing else:
```
$ opt -passes='inline,globalopt' empty.ll
opt: unknown cgscc pass 'globalopt'
```

Would be nice if there was something else, but the above works.

**Comment by aqjune** [comment] 2020-12-08 14:33
Yes, I think it would work. Maybe with small tweaks to appropriately deal with keywords such as requires.
Is it okay to write this in a language other than bash? I think writing this in bash might result in a bit of complex code. :/
python/php/perl?

**Comment by nunoplopes** [comment] 2020-12-08 15:33
Isn't smth like this enough? This is trivial in bash:
```
for each arg:
  if echo $arg | grep -passes=p:
    str=`opt -S -passes=$p,globalopt 2>&1`
    if error:
      p=$errorstr($p)
    arg=-passes=tv,$arg,tv
    break
```

If you think it is horrible and requires further cases, then yes, chose whatever language. Maybe python is the best as it's already a dependency for running LLVM's unit tests with lit.

**Closed** 2020-12-14 14:42 UTC
